import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
      flex: 1,
      backgroundColor: Platform.OS === "web" ? "#fff" : "#7c3aed",
    },
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: "#fff",
      width: "100%",
      maxWidth: Platform.OS === "web" ? 600 : "100%",
      marginHorizontal: Platform.OS === "web" ? "auto" : 0,
    },
    imageContainer: {
      marginTop: 20,
      borderRadius: 15,
      overflow: "hidden",
      marginBottom: 20,
    },
    image: {
      width: "100%",
      height: 150,
    },
    titleContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: "#7c3aed",
      textAlign: 'center'
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 20,
    },
    input: {
      flex: 1,
      height: 50,
      borderTopLeftRadius: 25,
      borderBottomLeftRadius: 25,
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
      backgroundColor: "#f0f0f0",
      paddingHorizontal: 15,
      fontSize: 16,
      borderColor: "transparent",
      borderWidth: 1,
      outlineWidth: 0,
    },
        inputFocused: {
          borderColor: "#7c3aed", 
          borderWidth: 1,
          borderStyle: "solid",
        },
    button: {
      height: 50,
      width: 50,
      backgroundColor: "#7c3aed",
      borderTopRightRadius: 25,
      borderBottomRightRadius: 25,
      justifyContent: "center",
      alignItems: "center",
    },
    loader: {
      marginTop: 20,
    },
    recipeContainer: {
      marginTop: 20,
    },
    card: {
      flexDirection: "row",
      backgroundColor: "#f9f9f9",
      borderRadius: 10,
      padding: 10,
      marginBottom: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginBottom: 20,
      flex: 1,
    },
    cardImage: {
      width: 100,
      height: 100,
      borderRadius: 10,
    },
    cardContent: {
      flex: 1,
      marginLeft: 10,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 5,
    },
    cardText: {
      fontSize: 14,
      color: "#555",
    },
    cafecitoButton: {
      marginTop: 20,
      alignItems: 'center',
    },
    cafecitoImage: {
      width: 200,
      height: 50,
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
      paddingHorizontal: 20,
    },
    modalView: {
      backgroundColor: "#fff",
      borderRadius: 10,
      padding: 20,
      maxWidth: Platform.OS === "web" ? 600 : "100%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#7c3aed',
      textAlign: 'center',
      marginBottom: 20,
    },
    modalDescription: {
      fontSize: 16,
      color: '#333',
      textAlign: 'justify',
    },
    closeButton: {
      backgroundColor: "#7c3aed",
      borderRadius: 20,
      padding: 10,
      marginTop: 20,
      alignSelf: 'center',
    },
    textStyle: {
      color: "#fff",
      fontWeight: "bold",
      textAlign: "center",
    },
});
